### ISSUE TITLE
臺語入聲後壁幫補silent

### ISSUE THREAD

**Issue by sih4sing5hong5** [sih4sing5hong5/tai5-uan5_gian5-gi2_kang1-ku7#267]
https://g0v-tw.slack.com/archives/itaigi/p1470933062000846

liz
12:31 AM @sing5hong5 粉專有人傳訊(其實是我熟似的人)

哈囉！語音合成有出現入聲的多音節詞，入聲音節時長都過短，導致聽起來節奏都怪怪的。建議在入聲音節尾填入一小段 silence，讓「音節」總時長拉長到跟舒聲音節接近，或甚至相同。

理由是這樣：傳統描述跟一些語音實驗統計說「入聲較短」，其實是跟量測方法有關。「音節」完整時長是「聲母+元音+韻尾」，但因為入聲的韻尾 -ptkh 不釋放，常無法確知時長，通常就不計，只算入「聲母+元音」的部份而少了「韻尾」（其實是有一段空白停頓），所以也就造成「入聲字較短」的印象。

但如果觀察多音節詞，入聲韻尾其實會有一定長度的停頓，下個音節並不會馬上開始。台語基本節拍還是 syllable-timed language，無論什麼聲母、韻母、聲調，每個音節的長度落差並不會太大。

簡單來說：合成入聲字時「韻尾」部分可填上一小段空白。可以試試看效果如何，聽起來也許會比較自然。（可以比較一下合成出來的「博物館」跟教典真人錄音的「博物館」，或其他包含入聲的詞來調整）

**Comment by sih4sing5hong5** [comment]
@liz462 秀蓉的聲敢閣有這个問題？
合的聲佇：http://xn--p8s96olm5c.xn--v0qr21b.xn--kpry57d/%E8%AC%9B/%E5%8D%9A%E7%89%A9%E9%A4%A8

**Comment by liz462** [comment]
聽著加真自然！！
顛倒是雜音，有人共我講有tshā～tshā的聲，我家己聽有時有有時無，揣著規則才回報
