### ISSUE TITLE
轉音佮綜合標音考慮加拼音無合法無要緊的參數

### ISSUE THREAD

**Issue by sih4sing5hong5** [sih4sing5hong5/tai5-uan5_gian5-gi2_kang1-ku7#351]
語句有時陣有外來語 https://github.com/sih4sing5hong5/su5lui3-hun1kip4-hok8bu7/issues/8

轉音加`無合法音標`無要緊的參數
綜合標音預設拄著`無合法音標`嘛無要緊，因為愛輸出用的

**Comment by sih4sing5hong5** [comment]
`檢查音標有正確無`，到時另外一个函式好矣

**Comment by a8568730** [comment]
#358
