### ISSUE TITLE
你講啥我聽無

### ISSUE THREAD

**Issue by a8568730** [sih4sing5hong5/tai5-uan5_gian5-gi2_kang1-ku7#368]
Lí kóng siáⁿ góa ̍thiaⁿ bô

http://xn--p8s96olm5c.xn--v0qr21b.xn--kpry57d/%E8%AC%9B/L%C3%AD%20k%C3%B3ng%20si%C3%A1%E2%81%BF%20g%C3%B3a%20%CC%8Dthia%E2%81%BF%20b%C3%B4

**Comment by sih4sing5hong5** [comment]
是因為有一个` ̍`黏佇`thiann`頭前，所以` ̍thiann`查無辭典
